# Generated by Django 3.1.7 on 2021-03-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Kategoria')),
                ('description', models.TextField(max_length=512, null=True, verbose_name='Opis')),
                ('type', models.SmallIntegerField(choices=[(0, 'fundacja'), (1, 'organizacja pozarządowa'), (2, 'zbiórka lokalna')], default=0, verbose_name='Typ')),
                ('categories', models.ManyToManyField(to='charity.Category', verbose_name='Kagegoria')),
            ],
        ),
    ]
